import type { DifficultyLevel, Chapter } from "./types"

export function getChapterCountForDifficulty(difficulty: DifficultyLevel): number {
  switch (difficulty) {
    case "Beginner":
      return 2
    case "Intermediate":
      return 3
    case "Advanced":
      return 4
    default:
      return 2
  }
}

export function generateChapterTemplates(topic: string, difficulty: DifficultyLevel, hobbies: string[]): Chapter[] {
  const chapterCount = getChapterCountForDifficulty(difficulty)
  const chapters: Chapter[] = []

  const chapterTitles = {
    2: [`Introduction to ${topic}`, `Mastering ${topic} Fundamentals`],
    3: [`Getting Started with ${topic}`, `Intermediate ${topic} Techniques`, `Advanced ${topic} Applications`],
    4: [
      `${topic} Foundations`,
      `Core ${topic} Concepts`,
      `Advanced ${topic} Strategies`,
      `${topic} Mastery & Projects`,
    ],
  }

  const titles = chapterTitles[chapterCount as 2 | 3 | 4] || chapterTitles[2]

  for (let i = 0; i < chapterCount; i++) {
    chapters.push({
      id: `chapter-${i + 1}`,
      title: titles[i],
      content: `[Content will be generated by ChatGPT API for ${titles[i]}]\n\nThis chapter will cover essential concepts related to ${topic}, tailored to your interests in ${hobbies.join(", ")}.\n\nKey learning objectives:\n- Understand core principles\n- Apply practical techniques\n- Build real-world projects`,
      order: i + 1,
      isCompleted: false,
    })
  }

  return chapters
}
